#!/usr/bin/env python3
"""Export publications.json to the formats other systems ingest.

    python3 export.py

Writes into export/:
    publications.bib          all papers, for ORCID's "Import BibTeX"
    zenodo-<slug>.json        one Zenodo deposition payload per paper

publications.json stays the single source of truth, so the site, your ORCID
record and your Zenodo deposits cannot drift apart. Nothing here talks to a
network: ORCID and Zenodo both need a personal OAuth token, which is yours to
hold, not this script's.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).parent
OUT = ROOT / "export"
DATA = json.loads((ROOT / "publications.json").read_text(encoding="utf-8"))
AUTHOR = DATA["author"]

# Characters that are syntax in LaTeX and must be escaped inside a BibTeX field.
TEX = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
       "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def tex(s: str) -> str:
    out = s.replace("\\", r"\textbackslash{}")
    for ch, rep in TEX.items():
        out = out.replace(ch, rep)
    # Curly quotes survive fine; straight doubles are safe inside braces.
    return out


def bibtex(p: dict) -> str:
    # Double braces on the title stop BibTeX styles lowercasing NG-iRTS, MPLS/IP
    # and the like.
    fields = [
        ("author", AUTHOR["citation_name"]),
        ("title", "{" + tex(p["title"]) + "}"),
        ("journal", tex(p["journal"])),
        ("year", p["year"]),
        ("volume", p["volume"]),
        ("number", p["issue"]),
        ("pages", f"{p['firstpage']}--{p['lastpage']}" if p["firstpage"] else ""),
        ("issn", p["issn"]),
        ("doi", p["doi"] or ""),
        ("url", f"{DATA['site']['base_url']}/papers/{p['slug']}/"),
        ("abstract", tex(p["abstract"])),
        ("keywords", tex(", ".join(p.get("keywords", [])))),
    ]
    body = ",\n".join(f"  {k:<9}= {{{v}}}" for k, v in fields if v)
    return f"@article{{{p['bibtex_key']},\n{body}\n}}\n"


def zenodo(p: dict) -> dict:
    meta = {
        "upload_type": "publication",
        "publication_type": "article",
        "title": p["title"],
        "creators": [{
            "name": AUTHOR["citation_name"],
            "orcid": AUTHOR["orcid"],
            "affiliation": AUTHOR.get("affiliation", ""),
        }],
        # Zenodo renders description as HTML, so a plain paragraph is right.
        "description": f"<p>{p['abstract']}</p>",
        "publication_date": p["issue_date"],
        "keywords": p.get("keywords", []),
        "journal_title": p["journal"],
        "journal_volume": p["volume"],
        "journal_issue": p["issue"],
        "journal_pages": (f"{p['firstpage']}-{p['lastpage']}" if p["firstpage"] else ""),
        "access_right": "open",
        # Left unset on purpose. Depositing a publisher PDF under a licence the
        # journal did not grant is an infringement, not a metadata slip.
        "license": "REPLACE_ME",
        "related_identifiers": [{
            "identifier": f"{DATA['site']['base_url']}/papers/{p['slug']}/",
            "relation": "isIdenticalTo",
            "scheme": "url",
        }],
        "language": "eng",
    }
    if p["issn"]:
        meta["related_identifiers"].append(
            {"identifier": p["issn"], "relation": "isPartOf", "scheme": "issn"})
    return {"metadata": meta}


def main() -> int:
    OUT.mkdir(exist_ok=True)
    papers = DATA["papers"]

    bib = ["% Generated by export.py from publications.json -- do not edit by hand.",
           "% ORCID: Works -> Add -> Import BibTeX -> choose this file.",
           ""]
    bib += [bibtex(p) for p in papers]
    (OUT / "publications.bib").write_text("\n".join(bib), encoding="utf-8")

    for p in papers:
        (OUT / f"zenodo-{p['slug']}.json").write_text(
            json.dumps(zenodo(p), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"export/publications.bib  ({len(papers)} entries)")
    for p in papers:
        print(f"export/zenodo-{p['slug']}.json")

    missing = [p["slug"] for p in papers if not p["doi"]]
    if missing:
        print("\nno DOI yet (BibTeX omits the field for these):")
        for s in missing:
            print(f"  {s}")
        print("Mint on Zenodo, then set \"doi\" in publications.json and re-run "
              "this and build.py.")
    print("\nZenodo licence is REPLACE_ME in every payload -- set it from each "
          "journal's copyright page before depositing.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
